# -*- coding: utf-8 -*-
"""Recursao_26ago24.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bYYrzqtWx6F0Ra3CATjDIFRmXzX8u6I0

## Este notebook versa sobre recursao
"""

import time

def fibo(n:int, brink = {}):
  # n = numero final -- integer
  # serie de fibonacci
  # eliminar casos triviais
    if n == 0:
        return 0
        print('Nao há serie de fibonacci para zero')
    elif n == 1:
        return 1
        print ('Mesmo caso acima, nao ha serie Fibonacci para um')
    else:
        if n not in brink:
             brink[n] = fibo(n-1) + fibo(n-2)
        return brink[n]
        # return fibo(n-1) + fibo(n-2) # temos serie de fibonacci usando recursao

# teste de software com numero n variavel
n = 10
for i in range(n+1):
  start = time.time_ns()
  fibo(i)
  stop = time.time_ns()
  tempo = (stop - start)
  print(f'i =',i,'tempo =', tempo,'serie = ',fibo(i))



